apiVersion: v1
kind: Service
metadata:
  name: lbvotingappresult
spec:
  type: LoadBalancer
  selector:
    name: voting-result
    app: complete-voting-app
  ports:
  - port: 80
    targetPort: 80
  
