apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      name: db
  template:
    metadata:
      labels:
        name: db
        app: complete-voting-app
    spec:
      containers:
      - name: db
        image: postgres:9.5
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust