apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-pod
spec:
  selector:
    matchLabels:
      app: redis-pod
  template:
    metadata:
      labels:
        app: voting-app
    spec:
      containers:
      - name: redis-pod
        image: redis
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"