apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-pod
spec:
  selector:
    matchLabels:
      name: redis-pod
  template:
    metadata:
      labels:
        name: redis-pod
    spec:
      containers:
      - name: redis-pod
        image: redis
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"