apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-result
spec:
  replicas: 3
  selector:
    matchLabels:
      name: voting-result
  template:
    metadata:
      labels:
        name: voting-result
        app: complete-voting-app
    spec:
      containers:
      - name: voting-result
        image: eesprit/voting-app-result
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
