apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: voting-app
  template:
    metadata:
      labels:
        name: voting-app
        app: complete-voting-app
    spec:
      containers:
      - name: voting-app
        image: eesprit/voting-app-vote
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

