apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-result
spec:
  selector:
    matchLabels:
      app: voting-result
  template:
    metadata:
      labels:
        app: voting-app
    spec:
      containers:
      - name: voting-result
        image: eesprit/voting-app-result
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
