apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: voting-app
    spec:
      containers:
      - name: worker
        image: eesprit/voting-app-worker
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
